name: LaTeX Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest
    steps:
    - uses: actions/checkout@v4
    - name: Compile LaTeX document
      continue-on-error: true
      run: |
        pdflatex -interaction=nonstopmode main.tex
    - name: Generate indexed PDF
      continue-on-error: true
      run: |
        pdflatex -interaction=nonstopmode main.tex
    - name: Generate final PDF
      continue-on-error: true
      run: |
        pdflatex -interaction=nonstopmode main.tex
    - name: Upload PDF
      uses: actions/upload-artifact@v4
      with:
        name: PDF
        path: main.pdf
    - name: Commit Build PDF
      # Only run on main branch push (e.g. after pull request merge).
      if: github.event_name == 'push'
      run: |
        git config --global user.name "${{ github.event.commits[0].author.name }}"
        git config --global user.email "${{ github.event.commits[0].author.email }}"
        git commit -a -m "${{ github.event.commits[0].message }}"
        git push
    