name: LaTeX Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: main.tex
        args: -shell-escape
        # packages: [ "minted" ]
    - name: Upload PDF
      uses: actions/upload-artifact@v4
      with:
        name: PDF
        path: main.pdf
